important:

teljesítményelemzés
modellből -> feladat
incquery lookup -> minták felírása alapdolgok megkeresésére


almost important:

copyFiles -> Changed working directory to: E:\_TSYS\... wtf


not important:
opentracker in tmux
create custom logformatter
better archiver with live status updates
create javadoc
create small box for faster vagrant testing
monitor scp copy progress somehow