important:
----------

perf analysis in real lab


almost important:
----------

copyFiles -> Changed working directory to: E:\_TSYS\... wtf
env independent zippping + scripts
refine logging levels


not important:
----------
change to better logging framework
better archiver with live status updates/scp progress
create javadoc
create small box for faster vagrant testing


toask:
------------
model update after leeching starts?