# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.vm.box = "hashicorp/precise32"
	config.vm.box_check_update = false
	config.vbguest.auto_update = false
	config.vm.synced_folder "shared/", "/home/vagrant/shared"
	
	config.vm.provision "shell", privileged: false, path: "shared/clean_vm.sh", run: "always"
	config.vm.provision "fix-no-tty", type: "shell" do |s|
		s.privileged = false
		s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
	end
	
	config.vm.define "seeder", primary: true do |seeder|
		seeder.vm.hostname = "seeder"
		seeder.vm.network "private_network", ip: "192.168.100.101"
		seeder.vm.provision "shell", privileged: false, path: "shared/install_seeder.sh"
	end
	
	config.vm.define "leecher1", primary: false do |leecher1|
		leecher1.vm.hostname = "leecher1"
		leecher1.vm.network "private_network", ip: "192.168.100.111"
		leecher1.vm.provision "shell", privileged: false, path: "shared/install_leecher.sh"
	end
	
	config.vm.define "leecher2", primary: false do |leecher2|
		leecher2.vm.hostname = "leecher2"
		leecher2.vm.network "private_network", ip: "192.168.100.112"
		leecher2.vm.provision "shell", privileged: false, path: "shared/install_leecher.sh"
	end
	
	config.vm.define "leecher3", primary: false do |leecher3|
		leecher3.vm.hostname = "leecher3"
		leecher3.vm.network "private_network", ip: "192.168.100.113"
		leecher3.vm.provision "shell", privileged: false, path: "shared/install_leecher.sh"
	end
	
	config.vm.define "leecher4", primary: false do |leecher4|
		leecher4.vm.hostname = "leecher4"
		leecher4.vm.network "private_network", ip: "192.168.100.114"
		leecher4.vm.provision "shell", privileged: false, path: "shared/install_leecher.sh"
	end
	
	config.vm.define "leecher5", primary: false do |leecher5|
		leecher5.vm.hostname = "leecher5"
		leecher5.vm.network "private_network", ip: "192.168.100.115"
		leecher5.vm.provision "shell", privileged: false, path: "shared/install_leecher.sh"
	end
	
end
